{
 "title": "Prometheus Quotes Exporter",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "min_step_interval", "query": "1m,1h,4h,8h" }
  ]
 },
 "panels": [
  {
   "title": "RSI (7) / Core Metrics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(quotes_rsi_week_per_hour_rate{job=\"quote_stock\"})",
     "legendFormat": "All Quotes"
    },
    {
     "expr": "avg(quotes_rsi_week_per_hour_rate{symbol=\"^GSPC\"})",
     "legendFormat": "S&P500"
    }
   ]
  },
  {
   "title": "RSI (14) / Core Metrics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(quotes_rsi_weeks_per_hour_rate{job=\"quote_stock\"})",
     "legendFormat": "All Quotes"
    },
    {
     "expr": "avg(quotes_rsi_weeks_per_hour_rate{symbol=\"^GSPC\"})",
     "legendFormat": "S&P500"
    }
   ]
  },
  {
   "title": "RSI (7) / Each quote",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(quotes_rsi_week_per_hour_rate) by (symbol)"
    }
   ]
  },
  {
   "title": "Volume / Each stock",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "deriv(quotes_exporter_volume{job=\"quote_stock\"}[30m])"
    }
   ]
  }
 ]
}